[package]
name = "isthegymbusy"
version = "0.0.0"
edition = "2021"
default-run = "isthegymbusy"

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1

[dependencies]
axum = "0.6.18"
tokio = { version = "1.28.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace", "compression-br", "compression-gzip", "compression-deflate"] }

sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "offline"] }

config = "0.13.3"
dotenv = "0.15.0"

color-eyre = "0.6.2"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing-appender = "0.2.2"

displaydoc = "0.2.3"
thiserror = "1.0.40"

serde = { version = "1.0.160", features = ["derive"] }
parking_lot = "0.12.1"
reqwest = { version = "0.11.17", default-features = false, features = ["rustls-tls"] }
futures = "0.3.28"
regex = "1.8.1"
async-once-cell = "0.4.4"
memmap2 = "0.5.10"
bytemuck = { version = "1.13.1", features = ["derive"] }
include_dir = "0.7.3"
mime_guess = "2.0.4"
chrono = "0.4.24"
crc = "3.0.1"

[dev-dependencies]
rand = "0.8.5"
tempdir = "0.3.7"
