[package]
name = "isthegymbusy"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1

[dependencies]
axum = "0.6.4"
color-eyre = "0.6.2"
config = "0.13.3"
dotenv = "0.15.0"
maud = { git = "https://github.com/lambda-fairy/maud", rev = "daa4354", features = ["axum"] }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.25.0", features = ["full"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tower-http = { version = "0.3.5", features = ["trace", "compression-br", "compression-gzip", "compression-deflate"] }
displaydoc = "0.2.3"
thiserror = "1.0.38"
parking_lot = "0.12.1"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls"] }
futures = "0.3.26"
regex = "1.7.1"
