[package]
name = "isthegymbusy"
version = "0.0.0"
edition = "2021"
default-run = "isthegymbusy"

[profile.release]
lto = "thin"

[dependencies]
axum =  "0.7.3"
axum-extra = { version = "0.9.1", features = ["typed-header"] }
tokio = { version = "1.35.1", features = ["full"] }
tower-http = { version = "0.5.0", features = [
    "trace",
    "compression-br",
    "compression-gzip",
    "compression-deflate",
] }

sqlx = { version = "0.7.3", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }

config = "0.13.4"
dotenv = "0.15.0"

color-eyre = "0.6.2"
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
sentry = { version = "0.32.1", features = [
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
], default-features = false }
sentry-tracing = { version = "0.32.1", features = [
    "backtrace",
], default-features = false }

displaydoc = "0.2.4"
thiserror = "1.0.56"

serde = { version = "1.0.194", features = ["derive"] }
reqwest = { version = "0.11.23", default-features = false, features = [
    "rustls-tls",
] }
regex = "1.10.2"
include_dir = "0.7.3"
mime_guess = "2.0.4"
chrono = "0.4.31"
