[package]
name = "isthegymbusy"
version = "0.0.0"
edition = "2021"
default-run = "isthegymbusy"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
axum = { version = "0.6.18", features = ["headers"] }
tokio = { version = "1.28.2", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace", "compression-br", "compression-gzip", "compression-deflate"] }

sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "offline"] }

config = "0.13.3"
dotenv = "0.15.0"

color-eyre = "0.6.2"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
sentry = { version = "0.31.3", features = ["backtrace", "contexts", "panic", "reqwest", "rustls"], default-features = false }
sentry-tracing = { version = "0.31.3", features = ["backtrace"], default-features = false }

displaydoc = "0.2.4"
thiserror = "1.0.40"

serde = { version = "1.0.163", features = ["derive"] }
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls"] }
regex = "1.8.3"
include_dir = "0.7.3"
mime_guess = "2.0.4"
chrono = "0.4.26"
