# fly.toml file generated for isthegymbusy on 2023-02-10T16:56:41Z

app = "isthegymbusy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ADDRESS = "0.0.0.0:8080"
  FETCH_INTERVAL = "60"
  HISTORY_PATH = "/data/history"
  RUST_LOG = "info,tower_http::trace::on_request=warn"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
source="isthegymbusy_data"
destination="/data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 20000
    soft_limit = 15000
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "30s"
    restart_limit = 0
    timeout = "2s"
